# Title of this configuration file
title: "Camera Test"
# Tag that identifies this configuration file.
tag: "amz-2018-gotthard"
# Description of this configuration file
description: ""
# Author of this configuration file
author: ""

# Extraction rules
rules:
  raw-camera-output:
    plugin: "rbb_tools.plugins.video_extractor"
    config:
      frame_rate: 20
      frame_height: 480
      frame_width: 752
      text_x: 90
      text_y: 5
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.ExactMatchingRule"
        config:
          topics:
            /cam0/image_raw: "sensor_msgs/Image"
          remapping:
            /cam0/image_raw: "/image"
      - type: "rbb_tools.extraction.matchers.ExactMatchingRule"
        config:
          topics:
            /cam1/image_raw: "sensor_msgs/Image"
          remapping:
            /cam1/image_raw: "/image"
