# Title of this configuration file
title: "AADC HW ROS IMU and Groundtruth"
# Tag that identifies this configuration file.
tag: "aadc-hw-imu-vicon"
# Description of this configuration file
description: ""
# Author of this configuration file
author: ""

# Extraction rules
rules:
  imus-all:
    plugin: "rbb_tools.plugins.time_series"
    config:
      topics:
        /sensors/imu1/data_raw:
          # Sub sampling goes here
          name: "IMU1 Accel & Gyro"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
            angular_velocity.x:
              default_color: "#FF9090"
            angular_velocity.y:
              default_color: "#90FF90"
            angular_velocity.z:
              default_color: "#9090FF"  
        /sensors/imu2/data_raw:
          # Sub sampling goes here
          name: "IMU2 Accel & Gyro"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
            angular_velocity.x:
              default_color: "#FF9090"
            angular_velocity.y:
              default_color: "#90FF90"
            angular_velocity.z:
              default_color: "#9090FF"  
        /aadc_car/aadc_hw_drivers/imu_integrated/data_raw:
          # Sub sampling goes here
          name: "IMU AADC HW Accel & Gyro"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
            angular_velocity.x:
              default_color: "#FF9090"
            angular_velocity.y:
              default_color: "#90FF90"
            angular_velocity.z:
              default_color: "#9090FF"  
        /sensors/imu_tinker:
          # Sub sampling goes here
          name: "Tinkerforge IMU Accel & Gyro"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
            angular_velocity.x:
              default_color: "#FF9090"
            angular_velocity.y:
              default_color: "#90FF90"
            angular_velocity.z:
              default_color: "#9090FF"  
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.AllTopicsMatchingRule"
        config:
  
  imus-accel:
    plugin: "rbb_tools.plugins.time_series"
    config:
      topics:
        /sensors/imu1/data_raw:
          # Sub sampling goes here
          name: "IMU1 Accel"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
        /sensors/imu2/data_raw:
          # Sub sampling goes here
          name: "IMU2 Accel"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
        /aadc_car/aadc_hw_drivers/imu_integrated/data_raw:
          # Sub sampling goes here
          name: "IMU AADC HW Accel"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
        /sensors/imu_tinker:
          # Sub sampling goes here
          name: "Tinkerforge IMU Accel"
          # Series are the message fields to record
          series:
            linear_acceleration.x:
              default_color: "#FF0000"
            linear_acceleration.y:
              default_color: "#00FF00"
            linear_acceleration.z:
              default_color: "#0000FF"   
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.AllTopicsMatchingRule"
        config:

  imus-gyro:
    plugin: "rbb_tools.plugins.time_series"
    config:
      topics:
        /sensors/imu1/data_raw:
          # Sub sampling goes here
          name: "IMU1 Gyro"
          # Series are the message fields to record
          series:
            angular_velocity.x:
              default_color: "#FF0000"
            angular_velocity.y:
              default_color: "#00FF00"
            angular_velocity.z:
              default_color: "#0000FF"   
        /sensors/imu2/data_raw:
          # Sub sampling goes here
          name: "IMU2 Gyro"
          # Series are the message fields to record
          series:
            angular_velocity.x:
              default_color: "#FF0000"
            angular_velocity.y:
              default_color: "#00FF00"
            angular_velocity.z:
              default_color: "#0000FF"  
        /aadc_car/aadc_hw_drivers/imu_integrated/data_raw:
          # Sub sampling goes here
          name: "IMU AADC HW Gyro"
          # Series are the message fields to record
          series:
            angular_velocity.x:
              default_color: "#FF0000"
            angular_velocity.y:
              default_color: "#00FF00"
            angular_velocity.z:
              default_color: "#0000FF"  
        /sensors/imu_tinker:
          # Sub sampling goes here
          name: "Tinkerforge IMU Gyro"
          # Series are the message fields to record
          series:
            angular_velocity.x:
              default_color: "#FF0000"
            angular_velocity.y:
              default_color: "#00FF00"
            angular_velocity.z:
              default_color: "#0000FF"  
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.AllTopicsMatchingRule"
        config:

  imus-temps:
    plugin: "rbb_tools.plugins.time_series"
    config:
      topics:
        /sensors/imu1/temp:
          # Sub sampling goes here
          name: "IMU1 Temp"
          # Series are the message fields to record
          series:
            temperature:
              default_color: "#FF0000"
        /sensors/imu2/temp:
          # Sub sampling goes here
          name: "IMU2 Temp"
          # Series are the message fields to record
          series:
            temperature:
              default_color: "#FF0000"
    topic_matchers:
      - type: "rbb_tools.extraction.matchers.AllTopicsMatchingRule"
        config:

  matplotlib-rule:
    plugin: "rbb_tools.plugins.matplotlib_plotter"
    config:
      data:
        # # Vicon Cone Marker
        # - name: "vicon_cone_marker_x"
        #   type: "raw"
        #   topic: "/vicon/aadc17_cone_marker/aadc17_cone_marker.transform.translation.x"
        # - name: "vicon_cone_marker_y"
        #   type: "raw"
        #   topic: "/vicon/aadc17_cone_marker/aadc17_cone_marker.transform.translation.y"

        # Vicon AADC Car
        - name: "vicon_aadc_car_x"
          type: "raw"
          topic: "/vicon/aadc17_car/aadc17_car.transform.translation.x"
        - name: "vicon_aadc_car_y"
          type: "raw"
          topic: "/vicon/aadc17_car/aadc17_car.transform.translation.y"

      figures:
        xy_plot:
          title: "Truth XY"
          xlabel: "X"
          ylabel: "Y"
          aspect: "equal"
          legend: "best"
          width: 1500
          height: 1500
          plots:
            - type: "lineplot"
              x: "vicon_aadc_car_x"
              y: "vicon_aadc_car_y"
              kwargs:
                label: "Vicon"
            # - type: "lineplot"
            #   x: "vicon_x"
            #   y: "vicon_y"
            #   kwargs:
            #     label: "VICON"

    topic_matchers:
      - type: "rbb_tools.extraction.matchers.AllTopicsMatchingRule"
        config:




